from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
import os
from datetime import datetime

class PDFService:
    def __init__(self):
        # Fix path to point to backend/reports instead of root/reports
        self.reports_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../reports"))
        os.makedirs(self.reports_dir, exist_ok=True)

    def generate_report(self, data: dict):
        report_id = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        file_path = os.path.join(self.reports_dir, report_id)
        
        doc = SimpleDocTemplate(file_path, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []

        # Title
        elements.append(Paragraph("Health Assessment Report", styles['Title']))
        elements.append(Spacer(1, 12))

        # Date and Disclaimer
        elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        elements.append(Spacer(1, 12))
        
        disclaimer_style = styles['Italic']
        disclaimer_style.textColor = colors.red
        elements.append(Paragraph("DISCLAIMER: This report is generated by an AI assistant for preliminary guidance only. It is NOT a professional medical diagnosis. Please consult a doctor for official treatment.", disclaimer_style))
        elements.append(Spacer(1, 20))

        # Symptoms
        elements.append(Paragraph("Symptoms Reported:", styles['Heading2']))
        symptoms_text = ", ".join(data.get("symptoms", ["None reported"]))
        elements.append(Paragraph(symptoms_text, styles['Normal']))
        elements.append(Spacer(1, 12))

        # AI Observations
        elements.append(Paragraph("AI Observations:", styles['Heading2']))
        obs_data = [
            ["Observation", "Value"],
            ["Predicted Condition", data.get("condition", "N/A")],
            ["Risk Level", data.get("risk_level", "N/A")],
            ["Confidence", f"{data.get('confidence', 0)}%"]
        ]
        
        t = Table(obs_data, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Recommendations
        elements.append(Paragraph("Recommendations:", styles['Heading2']))
        recs = data.get("recommendations", "Please consult a healthcare professional for specific recommendations.")
        
        # Preserve markdown linebreaks and basic formatting in ReportLab
        recs = recs.replace('\n', '<br/>')
        # Remove bold asterisks to prevent rendering issues in plain text paragraph
        recs = recs.replace('**', '')
        
        elements.append(Paragraph(recs, styles['Normal']))

        doc.build(elements)
        return report_id

pdf_service = PDFService()
